# Generated by Django 4.2.5 on 2023-09-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_agenteinmobiliario_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local_comercial', 'Local Comercial'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
