# Generated by Django 4.2.5 on 2023-09-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_propiedad_delete_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteinmobiliario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='agenteinmobiliario',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
